# Parte 7 - Carga de Datos a BigQuery

In [1]:
from google.cloud import bigquery

client = bigquery.Client.from_service_account_json(
    "../credentials/retail-analytics-lab-grupo2-a4bfa003951d.json"
)

print("Conexión exitosa")

Conexión exitosa

LEER CSV

In [2]:
import pandas as pd

clientes_df = pd.read_csv("../datasets/clientes.csv")
productos_df = pd.read_csv("../datasets/productos.csv")
ventas_df = pd.read_csv("../datasets/ventas.csv")

CARGAR CLIENTES

In [3]:
tabla_id = "retail-analytics-lab-grupo2.retail_dw.clientes"

job = client.load_table_from_dataframe(
    clientes_df,
    tabla_id
)

job.result()

print("Clientes cargados")

c:\Users\luise\miniconda3\envs\bigquery_lab\Lib\site-packages\google\cloud\bigquery\_pandas_helpers.py:486: FutureWarning: Loading pandas DataFrame into BigQuery will require pandas-gbq package version 0.26.1 or greater in the future. Tried to import pandas-gbq and got: No module named 'pandas_gbq'
  warnings.warn(

Clientes cargados

CARGAR PRODUCTOS

In [4]:
tabla_id = "retail-analytics-lab-grupo2.retail_dw.productos"

job = client.load_table_from_dataframe(
    productos_df,
    tabla_id
)

job.result()

print("Productos cargados")

c:\Users\luise\miniconda3\envs\bigquery_lab\Lib\site-packages\google\cloud\bigquery\_pandas_helpers.py:486: FutureWarning: Loading pandas DataFrame into BigQuery will require pandas-gbq package version 0.26.1 or greater in the future. Tried to import pandas-gbq and got: No module named 'pandas_gbq'
  warnings.warn(

Productos cargados

In [5]:
print(ventas_df.dtypes)

ventas_df.info()

ventas_df.head()

id_venta         int64
fecha_venta        str
id_cliente       int64
id_producto      int64
sucursal           str
monto          float64
dtype: object
<class 'pandas.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 6 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   id_venta     100000 non-null  int64
 1   fecha_venta  100000 non-null  str
 2   id_cliente   100000 non-null  int64
 3   id_producto  100000 non-null  int64
 4   sucursal     100000 non-null  str
 5   monto        100000 non-null  float64
dtypes: float64(1), int64(3), str(2)
memory usage: 6.6 MB

   id_venta fecha_venta  id_cliente  id_producto     sucursal   monto
0         1  2025-03-19         234          301  Tegucigalpa  392.99
1         2  2025-03-07        3801          114     San José  120.91
2         3  2025-01-24        1774          306  Tegucigalpa  461.73
3         4  2025-02-24        3887          309  Tegucigalpa  435.45
4         5  2025-02-09        3527          354     San José  361.08

In [6]:
ventas_df.head()

   id_venta fecha_venta  id_cliente  id_producto     sucursal   monto
0         1  2025-03-19         234          301  Tegucigalpa  392.99
1         2  2025-03-07        3801          114     San José  120.91
2         3  2025-01-24        1774          306  Tegucigalpa  461.73
3         4  2025-02-24        3887          309  Tegucigalpa  435.45
4         5  2025-02-09        3527          354     San José  361.08

In [8]:
ventas_df["monto"].head()

0    392.99
1    120.91
2    461.73
3    435.45
4    361.08
Name: monto, dtype: float64

CARGAR VENTAS

In [9]:
from google.cloud import bigquery

schema = [
    bigquery.SchemaField("id_venta", "INT64"),
    bigquery.SchemaField("fecha_venta", "DATE"),
    bigquery.SchemaField("id_cliente", "INT64"),
    bigquery.SchemaField("id_producto", "INT64"),
    bigquery.SchemaField("sucursal", "STRING"),
    bigquery.SchemaField("monto", "FLOAT64"),
]

job_config = bigquery.LoadJobConfig(
    schema=schema,
    write_disposition="WRITE_TRUNCATE"
)

job = client.load_table_from_dataframe(
    ventas_df,
    "retail-analytics-lab-grupo2.retail_dw.ventas",
    job_config=job_config
)

job.result()

print("Ventas cargadas correctamente")

c:\Users\luise\miniconda3\envs\bigquery_lab\Lib\site-packages\google\cloud\bigquery\_pandas_helpers.py:486: FutureWarning: Loading pandas DataFrame into BigQuery will require pandas-gbq package version 0.26.1 or greater in the future. Tried to import pandas-gbq and got: No module named 'pandas_gbq'
  warnings.warn(

Ventas cargadas correctamente

VERIFICACION

In [10]:
query = """
SELECT COUNT(*) total
FROM retail_dw.ventas
"""

resultado = client.query(query).to_dataframe()

resultado

c:\Users\luise\miniconda3\envs\bigquery_lab\Lib\site-packages\google\cloud\bigquery\table.py:2082: UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.
  warnings.warn(

    total
0  100000